/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

public class App {
    public static void main(String[] args) {
        Connection conn = null;
        ResultSet rs = null;
        Statement stmt = null;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection(
                    "jdbc:mysql://proxysql1:6033/test?"
                            + "useServerPrepStmts=true&"
                            + "characterEncoding=utf-8&"
                            + "useSSL=false&useCursorFetch=true&"
                            + "defaultFetchSize=1000",
                    "root", "t00r");
            conn.setReadOnly(true);
            stmt = conn.createStatement();
            stmt.setQueryTimeout(10);
            // stmt.setFetchSize(100);
            rs = stmt.executeQuery("select c from x");
            rs.setFetchSize(100);
            while (rs.next()) {
                System.out.println(rs.getString("c"));
            }

            rs.close();
            stmt.close();
            conn.close();
        } catch (Exception e) {
            System.out.println("SQLException");
            e.printStackTrace();
        }
    }
}
